export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type LeadStatus = "new" | "in_progress" | "answered" | "closed";

export type Database = {
  public: {
    Tables: {
      branches: {
        Row: {
          id: string;
          name_lt: string;
          name_en: string | null;
          slug_lt: string;
          slug_en: string | null;
          short_description_lt: string;
          short_description_en: string | null;
          full_description_lt: string;
          full_description_en: string | null;
          address_lt: string;
          address_en: string | null;
          city: string;
          postal_code: string | null;
          phone: string;
          email: string | null;
          map_url: string | null;
          latitude: number | null;
          longitude: number | null;
          parking_info_lt: string | null;
          parking_info_en: string | null;
          transport_info_lt: string | null;
          transport_info_en: string | null;
          cover_image_url: string | null;
          gallery_preview_image_url: string | null;
          booking_url: string | null;
          opening_hours_json: Json;
          trust_points_lt: Json;
          trust_points_en: Json;
          is_active: boolean;
          sort_order: number;
          meta_title_lt: string | null;
          meta_title_en: string | null;
          meta_description_lt: string | null;
          meta_description_en: string | null;
          og_image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name_lt: string;
          name_en?: string | null;
          slug_lt: string;
          slug_en?: string | null;
          short_description_lt: string;
          short_description_en?: string | null;
          full_description_lt: string;
          full_description_en?: string | null;
          address_lt: string;
          address_en?: string | null;
          city?: string;
          postal_code?: string | null;
          phone: string;
          email?: string | null;
          map_url?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          parking_info_lt?: string | null;
          parking_info_en?: string | null;
          transport_info_lt?: string | null;
          transport_info_en?: string | null;
          cover_image_url?: string | null;
          gallery_preview_image_url?: string | null;
          booking_url?: string | null;
          opening_hours_json?: Json;
          trust_points_lt?: Json;
          trust_points_en?: Json;
          is_active?: boolean;
          sort_order?: number;
          meta_title_lt?: string | null;
          meta_title_en?: string | null;
          meta_description_lt?: string | null;
          meta_description_en?: string | null;
          og_image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["branches"]["Insert"]>;
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          title_lt: string;
          title_en: string | null;
          slug_lt: string;
          slug_en: string | null;
          short_description_lt: string;
          short_description_en: string | null;
          full_description_lt: string;
          full_description_en: string | null;
          category: string;
          starting_price: number | null;
          currency_code: string;
          price_note_lt: string | null;
          price_note_en: string | null;
          duration_minutes: number | null;
          cover_image_url: string | null;
          benefits_lt: Json;
          benefits_en: Json;
          faq_lt: Json;
          faq_en: Json;
          is_featured: boolean;
          is_published: boolean;
          sort_order: number;
          meta_title_lt: string | null;
          meta_title_en: string | null;
          meta_description_lt: string | null;
          meta_description_en: string | null;
          og_image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_lt: string;
          title_en?: string | null;
          slug_lt: string;
          slug_en?: string | null;
          short_description_lt: string;
          short_description_en?: string | null;
          full_description_lt: string;
          full_description_en?: string | null;
          category: string;
          starting_price?: number | null;
          currency_code?: string;
          price_note_lt?: string | null;
          price_note_en?: string | null;
          duration_minutes?: number | null;
          cover_image_url?: string | null;
          benefits_lt?: Json;
          benefits_en?: Json;
          faq_lt?: Json;
          faq_en?: Json;
          is_featured?: boolean;
          is_published?: boolean;
          sort_order?: number;
          meta_title_lt?: string | null;
          meta_title_en?: string | null;
          meta_description_lt?: string | null;
          meta_description_en?: string | null;
          og_image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["services"]["Insert"]>;
        Relationships: [];
      };
      service_branch_availability: {
        Row: {
          id: string;
          service_id: string;
          branch_id: string;
          is_available: boolean;
          branch_specific_price_note_lt: string | null;
          branch_specific_price_note_en: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_id: string;
          branch_id: string;
          is_available?: boolean;
          branch_specific_price_note_lt?: string | null;
          branch_specific_price_note_en?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["service_branch_availability"]["Insert"]>;
        Relationships: [];
      };
      specialists: {
        Row: {
          id: string;
          full_name: string;
          role_lt: string;
          role_en: string | null;
          bio_lt: string | null;
          bio_en: string | null;
          photo_url: string | null;
          years_experience: number | null;
          specialties_lt: Json;
          specialties_en: Json;
          branch_id: string | null;
          is_featured: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          role_lt: string;
          role_en?: string | null;
          bio_lt?: string | null;
          bio_en?: string | null;
          photo_url?: string | null;
          years_experience?: number | null;
          specialties_lt?: Json;
          specialties_en?: Json;
          branch_id?: string | null;
          is_featured?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["specialists"]["Insert"]>;
        Relationships: [];
      };
      gallery_items: {
        Row: {
          id: string;
          title_lt: string;
          title_en: string | null;
          description_lt: string | null;
          description_en: string | null;
          alt_text_lt: string;
          alt_text_en: string | null;
          image_url: string;
          image_public_id: string | null;
          service_id: string | null;
          branch_id: string | null;
          specialist_id: string | null;
          category: string | null;
          tags_lt: Json;
          tags_en: Json;
          is_before_after: boolean;
          before_image_url: string | null;
          after_image_url: string | null;
          is_featured: boolean;
          is_visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_lt: string;
          title_en?: string | null;
          description_lt?: string | null;
          description_en?: string | null;
          alt_text_lt: string;
          alt_text_en?: string | null;
          image_url: string;
          image_public_id?: string | null;
          service_id?: string | null;
          branch_id?: string | null;
          specialist_id?: string | null;
          category?: string | null;
          tags_lt?: Json;
          tags_en?: Json;
          is_before_after?: boolean;
          before_image_url?: string | null;
          after_image_url?: string | null;
          is_featured?: boolean;
          is_visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["gallery_items"]["Insert"]>;
      };
      promotions: {
        Row: {
          id: string;
          title_lt: string;
          title_en: string | null;
          description_lt: string;
          description_en: string | null;
          banner_image_url: string | null;
          discount_label_lt: string | null;
          discount_label_en: string | null;
          cta_text_lt: string | null;
          cta_text_en: string | null;
          cta_url: string | null;
          branch_id: string | null;
          service_id: string | null;
          starts_at: string | null;
          ends_at: string | null;
          is_featured: boolean;
          is_active: boolean;
          sort_order: number;
          meta_title_lt: string | null;
          meta_title_en: string | null;
          meta_description_lt: string | null;
          meta_description_en: string | null;
          og_image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_lt: string;
          title_en?: string | null;
          description_lt: string;
          description_en?: string | null;
          banner_image_url?: string | null;
          discount_label_lt?: string | null;
          discount_label_en?: string | null;
          cta_text_lt?: string | null;
          cta_text_en?: string | null;
          cta_url?: string | null;
          branch_id?: string | null;
          service_id?: string | null;
          starts_at?: string | null;
          ends_at?: string | null;
          is_featured?: boolean;
          is_active?: boolean;
          sort_order?: number;
          meta_title_lt?: string | null;
          meta_title_en?: string | null;
          meta_description_lt?: string | null;
          meta_description_en?: string | null;
          og_image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["promotions"]["Insert"]>;
      };
      blog_posts: {
        Row: {
          id: string;
          title_lt: string;
          title_en: string | null;
          slug_lt: string;
          slug_en: string | null;
          excerpt_lt: string;
          excerpt_en: string | null;
          body_lt: Json;
          body_en: Json;
          cover_image_url: string | null;
          cover_alt_text_lt: string | null;
          cover_alt_text_en: string | null;
          author_name: string;
          category: string;
          tags_json: Json;
          related_branch_id: string | null;
          related_service_id: string | null;
          published_at: string | null;
          is_published: boolean;
          is_featured: boolean;
          meta_title_lt: string | null;
          meta_title_en: string | null;
          meta_description_lt: string | null;
          meta_description_en: string | null;
          og_image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_lt: string;
          title_en?: string | null;
          slug_lt: string;
          slug_en?: string | null;
          excerpt_lt: string;
          excerpt_en?: string | null;
          body_lt?: Json;
          body_en?: Json;
          cover_image_url?: string | null;
          cover_alt_text_lt?: string | null;
          cover_alt_text_en?: string | null;
          author_name: string;
          category: string;
          tags_json?: Json;
          related_branch_id?: string | null;
          related_service_id?: string | null;
          published_at?: string | null;
          is_published?: boolean;
          is_featured?: boolean;
          meta_title_lt?: string | null;
          meta_title_en?: string | null;
          meta_description_lt?: string | null;
          meta_description_en?: string | null;
          og_image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["blog_posts"]["Insert"]>;
      };
      testimonials: {
        Row: {
          id: string;
          customer_name: string;
          quote_lt: string;
          quote_en: string | null;
          rating: number | null;
          branch_id: string | null;
          service_id: string | null;
          is_featured: boolean;
          is_visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_name: string;
          quote_lt: string;
          quote_en?: string | null;
          rating?: number | null;
          branch_id?: string | null;
          service_id?: string | null;
          is_featured?: boolean;
          is_visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["testimonials"]["Insert"]>;
      };
      leads: {
        Row: {
          id: string;
          full_name: string;
          phone: string | null;
          email: string | null;
          preferred_branch_id: string | null;
          message: string;
          source_page: string | null;
          status: LeadStatus;
          internal_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          phone?: string | null;
          email?: string | null;
          preferred_branch_id?: string | null;
          message: string;
          source_page?: string | null;
          status?: LeadStatus;
          internal_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["leads"]["Insert"]>;
      };
      site_settings: {
        Row: {
          id: string;
          settings_key: string;
          business_name: string;
          default_phone: string | null;
          default_email: string | null;
          logo_url: string | null;
          favicon_url: string | null;
          social_instagram: string | null;
          social_facebook: string | null;
          social_tiktok: string | null;
          footer_text_lt: string | null;
          footer_text_en: string | null;
          default_meta_title_lt: string | null;
          default_meta_title_en: string | null;
          default_meta_description_lt: string | null;
          default_meta_description_en: string | null;
          analytics_ga4_id: string | null;
          theme_color: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          settings_key?: string;
          business_name: string;
          default_phone?: string | null;
          default_email?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          social_instagram?: string | null;
          social_facebook?: string | null;
          social_tiktok?: string | null;
          footer_text_lt?: string | null;
          footer_text_en?: string | null;
          default_meta_title_lt?: string | null;
          default_meta_title_en?: string | null;
          default_meta_description_lt?: string | null;
          default_meta_description_en?: string | null;
          analytics_ga4_id?: string | null;
          theme_color?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["site_settings"]["Insert"]>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
