begin;

create extension if not exists pgcrypto;

create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(),
  name_lt text not null,
  name_en text,
  slug_lt text not null unique,
  slug_en text unique,
  short_description_lt text not null,
  short_description_en text,
  full_description_lt text not null,
  full_description_en text,
  address_lt text not null,
  address_en text,
  city text not null default 'Vilnius',
  postal_code text,
  phone text not null,
  email text,
  map_url text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  parking_info_lt text,
  parking_info_en text,
  transport_info_lt text,
  transport_info_en text,
  cover_image_url text,
  gallery_preview_image_url text,
  booking_url text,
  opening_hours_json jsonb not null default '[]'::jsonb,
  trust_points_lt jsonb not null default '[]'::jsonb,
  trust_points_en jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  meta_title_lt text,
  meta_title_en text,
  meta_description_lt text,
  meta_description_en text,
  og_image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  title_lt text not null,
  title_en text,
  slug_lt text not null unique,
  slug_en text unique,
  short_description_lt text not null,
  short_description_en text,
  full_description_lt text not null,
  full_description_en text,
  category text not null,
  starting_price numeric(10, 2),
  currency_code text not null default 'EUR',
  price_note_lt text,
  price_note_en text,
  duration_minutes integer,
  cover_image_url text,
  benefits_lt jsonb not null default '[]'::jsonb,
  benefits_en jsonb not null default '[]'::jsonb,
  faq_lt jsonb not null default '[]'::jsonb,
  faq_en jsonb not null default '[]'::jsonb,
  is_featured boolean not null default false,
  is_published boolean not null default false,
  sort_order integer not null default 0,
  meta_title_lt text,
  meta_title_en text,
  meta_description_lt text,
  meta_description_en text,
  og_image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.service_branch_availability (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  is_available boolean not null default true,
  branch_specific_price_note_lt text,
  branch_specific_price_note_en text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (service_id, branch_id)
);

create table if not exists public.specialists (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  role_lt text not null,
  role_en text,
  bio_lt text,
  bio_en text,
  photo_url text,
  years_experience integer,
  specialties_lt jsonb not null default '[]'::jsonb,
  specialties_en jsonb not null default '[]'::jsonb,
  branch_id uuid references public.branches(id) on delete set null,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.gallery_items (
  id uuid primary key default gen_random_uuid(),
  title_lt text not null,
  title_en text,
  description_lt text,
  description_en text,
  alt_text_lt text not null,
  alt_text_en text,
  image_url text not null,
  image_public_id text,
  service_id uuid references public.services(id) on delete set null,
  branch_id uuid references public.branches(id) on delete set null,
  specialist_id uuid references public.specialists(id) on delete set null,
  category text,
  tags_lt jsonb not null default '[]'::jsonb,
  tags_en jsonb not null default '[]'::jsonb,
  is_before_after boolean not null default false,
  before_image_url text,
  after_image_url text,
  is_featured boolean not null default false,
  is_visible boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.promotions (
  id uuid primary key default gen_random_uuid(),
  title_lt text not null,
  title_en text,
  description_lt text not null,
  description_en text,
  banner_image_url text,
  discount_label_lt text,
  discount_label_en text,
  cta_text_lt text,
  cta_text_en text,
  cta_url text,
  branch_id uuid references public.branches(id) on delete set null,
  service_id uuid references public.services(id) on delete set null,
  starts_at timestamptz,
  ends_at timestamptz,
  is_featured boolean not null default false,
  is_active boolean not null default false,
  sort_order integer not null default 0,
  meta_title_lt text,
  meta_title_en text,
  meta_description_lt text,
  meta_description_en text,
  og_image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title_lt text not null,
  title_en text,
  slug_lt text not null unique,
  slug_en text unique,
  excerpt_lt text not null,
  excerpt_en text,
  body_lt jsonb not null default '[]'::jsonb,
  body_en jsonb not null default '[]'::jsonb,
  cover_image_url text,
  cover_alt_text_lt text,
  cover_alt_text_en text,
  author_name text not null,
  category text not null,
  tags_json jsonb not null default '[]'::jsonb,
  related_branch_id uuid references public.branches(id) on delete set null,
  related_service_id uuid references public.services(id) on delete set null,
  published_at timestamptz,
  is_published boolean not null default false,
  is_featured boolean not null default false,
  meta_title_lt text,
  meta_title_en text,
  meta_description_lt text,
  meta_description_en text,
  og_image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.testimonials (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  quote_lt text not null,
  quote_en text,
  rating smallint,
  branch_id uuid references public.branches(id) on delete set null,
  service_id uuid references public.services(id) on delete set null,
  is_featured boolean not null default false,
  is_visible boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text,
  email text,
  preferred_branch_id uuid references public.branches(id) on delete set null,
  message text not null,
  source_page text,
  status text not null default 'new',
  internal_note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint leads_status_check check (status in ('new', 'in_progress', 'answered', 'closed'))
);

create table if not exists public.site_settings (
  id uuid primary key default gen_random_uuid(),
  settings_key text not null default 'default' unique,
  business_name text not null,
  default_phone text,
  default_email text,
  logo_url text,
  favicon_url text,
  social_instagram text,
  social_facebook text,
  social_tiktok text,
  footer_text_lt text,
  footer_text_en text,
  default_meta_title_lt text,
  default_meta_title_en text,
  default_meta_description_lt text,
  default_meta_description_en text,
  analytics_ga4_id text,
  theme_color text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

commit;
